#!/bin/bash
# Initializes a new Python repository.

readonly RANDOM_STRING="$(tr -dc "A-Za-z0-9" < /dev/urandom | head -c 6)"

if [[ -n "$1" ]]; then
  readonly NEW_PROJECT_DIRECTORY="$1"
else
  # Avoid directory name clashes.
  readonly NEW_PROJECT_DIRECTORY="python-new-project_${RANDOM_STRING}"
fi

git clone git@github.com:gpwaob92679/python-new-project.git "${NEW_PROJECT_DIRECTORY}" || exit
cd "$1" || exit

rm -rf .git
git init
echo "# $1" > README.md
pre-commit install

# git add .
# git commit -m "Initial commit"

echo "Successfully initialized repository"
echo "Please proceed to edit README.md"
