#!/bin/bash

# Initializes a new Python repository.

git clone git@github.com:gpwaob92679/python-new-project.git
mv python-new-project "$1"
cd "$1" || exit

rm -rf .git
git init

echo "# $1" > README.md
pre-commit install

# git add .
# git commit -m "Initial commit"

echo "Successfully initialized repository"
echo "Please proceed to edit README.md"
